name: Deploy Resources to Azure
on:
  push:
     branches: [ "main" ]


permissions:
  id-token: write
  contents: read

jobs:
  terraform_deploy:
    runs-on: ubuntu-latest
    environment: prod
    
    steps:
    - name: Action Checkout
      uses: actions/checkout@v3
     
    - name: Azure Login
      uses: azure/login@v2
      with:
        tenant-id: ${{ secrets.TENANT_ID }}
        client-id: ${{ secrets.CLIENT_ID }}
        subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

    - name: Install Terraform
      uses: little-core-labs/install-terraform@v2.0.0
      with:
          version: 0.13.4
    - name: Terraform apply
      run: |
        cd azure
        terraform init
        terraform plan
        terraform apply -auto-approve
    

