name: Azure Terrform Plan
on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'azure/**'
  workflow_dispatch:

permissions:
    id-token: write
    issues: write
    pull-requests: write
    contents: read

jobs:
    terraform_plan:
        runs-on: windows-latest
        environment: prod
    
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Terraform Plan
            uses: ./.github/actions/terraformplan/action.yml
            with:
                working-directory: azure
