name: Azure Terrform Plan
on:
  pull_request:
    branches:
      - main
      - dev

  workflow_dispatch:

permissions:
    id-token: write
    issues: write
    pull-requests: write
    contents: read


jobs:
    deploy_to_Development:
        runs-on: ubuntu-latest
        environment: dev
        defaults:
            run:
              working-directory: ./azure/deploy
    
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Azure Login
          uses: azure/login@v2
          with:
            tenant-id: ${{ secrets.TENANT_ID }}
            client-id: ${{ secrets.CLIENT_ID }}
            subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
        
        - name: Terraform Plan Action
          uses: ./.github/actions/terraformplan
          with:
            working-directory: './azure/deploy'
            RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }}
            STORAGE_ACCOUNT: ${{ vars.STORAGE_ACCOUNT }}
            CONTAINER_NAME: ${{ vars.CONTAINER_NAME }}
            client-id: ${{ secrets.CLIENT_ID }}
            tenant-id: ${{ secrets.TENANT_ID }}
            subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
            envrionment_run: 'dev'

    
        - name: Terraform Apply
          uses: ./.github/actions/terraformapply
          with:
            working-directory: './azure/deploy'
            RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }}
            STORAGE_ACCOUNT: ${{ vars.STORAGE_ACCOUNT }}
            CONTAINER_NAME: ${{ vars.CONTAINER_NAME }}
            client-id: ${{ secrets.CLIENT_ID }}
            tenant-id: ${{ secrets.TENANT_ID }}
            subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
  
    deploy_to_Production:
        runs-on: ubuntu-latest
        environment: prod
        needs: [deploy_to_Development]
        defaults:
            run:
              working-directory: ./azure/deploy
    
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Azure Login
          uses: azure/login@v2
          with:
            tenant-id: ${{ secrets.TENANT_ID }}
            client-id: ${{ secrets.CLIENT_ID }}
            subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
        
        - name: Terraform Plan Action
          uses: ./.github/actions/terraformplan
          with:
            working-directory: './azure/deploy'
            RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }}
            STORAGE_ACCOUNT: ${{ vars.STORAGE_ACCOUNT }}
            CONTAINER_NAME: ${{ vars.CONTAINER_NAME }}
            client-id: ${{ secrets.CLIENT_ID }}
            tenant-id: ${{ secrets.TENANT_ID }}
            subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
            envrionment_run: 'prod'
    
        - name: Terraform Apply
          uses: ./.github/actions/terraformapply
          with:
            working-directory: './azure/deploy'
            RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }}
            STORAGE_ACCOUNT: ${{ vars.STORAGE_ACCOUNT }}
            CONTAINER_NAME: ${{ vars.CONTAINER_NAME }}
            client-id: ${{ secrets.CLIENT_ID }}
            tenant-id: ${{ secrets.TENANT_ID }}
            subscription-id: ${{ secrets.SUBSCRIPTION_ID }}