name: Azure Terrform Plan
on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'azure/**'
  workflow_dispatch:

permissions:
    id-token: write
    issues: write
    pull-requests: write
    contents: read

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_USE_AZUREAD: true

jobs:
    terraform_plan:
        runs-on: ubuntu-latest
        environment: prod
        defaults:
            run:
              working-directory: ./azure/deploy
    
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Terraform Plan Action
          uses: ./.github/actions/terraformplan
          with:
            RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }}
            STORAGE_ACCOUNT: ${{ vars.STORAGE_ACCOUNT }}
            CONTAINER_NAME: ${{ vars.CONTAINER_NAME }}