name: List services in GCP
on:
  push:
     branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  Get_OIDC_ID_token:
    runs-on: ubuntu-latest
    environment: prod
    
    steps:
    - name: Action Checkout
      uses: actions/checkout@v3
     
    - name: GCP OIDC Login
      id: auth
      uses: 'google-github-actions/auth@v2'
      with:
        service_account: oidc-account@unified-adviser-447010-g9.iam.gserviceaccount.com
        workload_identity_provider: projects/420668524245/locations/global/workloadIdentityPools/github/providers/github-openid

    - name: GCloud SDK
      uses: 'google-github-actions/setup-gcloud@v1'
      with: 
        version: '>= 418.0.0'

    - id: 'gcloud'
      name: 'gcloud'
      run: |
        gcloud storage buckets create gs://first-bucket90 --location=us-east1
